@echo off

REM Verifica se o ambiente virtual existe
if not exist .venv (
    echo Criando ambiente virtual...
    python -m venv .venv
    echo Ativando ambiente virtual...
    call .venv\Scripts\activate.bat
    call python -m pip install --upgrade pip
    echo Instalando dependências...
    call pip install -r requirements.txt
    echo Finalizado instalacao de dependências...
) else (
    echo Ambiente virtual já existe...
    call .venv\Scripts\activate.bat
    echo Ambiente virtual ativado...
)

echo Iniciando streamlit app...
call streamlit run src\run_streamlit.py

exit /b